apiVersion: v1
kind: Service
metadata:
  name: forgedesk-server
  namespace: smartpm
spec:
  type: ClusterIP
  selector:
    app: forgedesk
    component: server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
